-- Smart Tuisyen / Supabase starter schema
-- Run this in Supabase SQL Editor after creating your project.
-- IMPORTANT: never expose service_role keys in GitHub Pages.

create type public.user_role as enum ('student','parent','teacher','admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  phone text,
  role public.user_role not null default 'student',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table public.classes (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete set null,
  teacher_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  form_level text,
  created_at timestamptz not null default now()
);

create table public.class_members (
  class_id bigint references public.classes(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(class_id,user_id)
);

create table public.live_classes (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz,
  meeting_url text,
  status text not null default 'scheduled',
  created_at timestamptz not null default now()
);

create table public.recorded_lessons (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  title text not null,
  video_url text not null,
  duration_seconds int,
  created_at timestamptz not null default now()
);

create table public.notes (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete set null,
  title text not null,
  file_url text not null,
  created_at timestamptz not null default now()
);

create table public.homework (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  teacher_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  due_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.homework_submissions (
  id bigint generated by default as identity primary key,
  homework_id bigint references public.homework(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  answer_text text,
  file_url text,
  status text not null default 'submitted',
  mark numeric,
  feedback text,
  submitted_at timestamptz not null default now(),
  unique(homework_id,student_id)
);

create table public.quizzes (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  teacher_id uuid references public.profiles(id) on delete set null,
  title text not null,
  duration_minutes int default 15,
  created_at timestamptz not null default now()
);

create table public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.quizzes(id) on delete cascade,
  question text not null,
  question_type text not null default 'mcq',
  options jsonb,
  correct_answer text
);

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.quizzes(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  score numeric,
  started_at timestamptz default now(),
  submitted_at timestamptz
);

create table public.chat_rooms (
  id bigint generated by default as identity primary key,
  name text,
  is_group boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.chat_members (
  room_id bigint references public.chat_rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  joined_at timestamptz default now(),
  primary key(room_id,user_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  room_id bigint references public.chat_rooms(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete cascade,
  body text,
  attachment_url text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  type text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.attendance (
  id bigint generated by default as identity primary key,
  live_class_id bigint references public.live_classes(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  joined_at timestamptz,
  left_at timestamptz
);

create table public.student_progress (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete cascade,
  progress_percent numeric default 0,
  learning_minutes int default 0,
  updated_at timestamptz default now(),
  unique(student_id,subject_id)
);

create table public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  plan text not null,
  status text not null default 'active',
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz default now()
);

create index messages_room_created_idx on public.messages(room_id,created_at);
create index notifications_user_created_idx on public.notifications(user_id,created_at);
create index homework_class_due_idx on public.homework(class_id,due_at);

alter table public.profiles enable row level security;
alter table public.class_members enable row level security;
alter table public.messages enable row level security;
alter table public.chat_members enable row level security;
alter table public.notifications enable row level security;
alter table public.homework_submissions enable row level security;

-- Basic user policies. Expand carefully for production.
create policy "profiles_self_read" on public.profiles
for select using (auth.uid() = id);

create policy "profiles_self_update" on public.profiles
for update using (auth.uid() = id);

create policy "chat_members_self_read" on public.chat_members
for select using (auth.uid() = user_id);

create policy "messages_members_read" on public.messages
for select using (
  exists (
    select 1 from public.chat_members cm
    where cm.room_id = messages.room_id and cm.user_id = auth.uid()
  )
);

create policy "messages_members_insert" on public.messages
for insert with check (
  sender_id = auth.uid() and exists (
    select 1 from public.chat_members cm
    where cm.room_id = messages.room_id and cm.user_id = auth.uid()
  )
);

create policy "notifications_self" on public.notifications
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
